- src/main/java/com/arangodb/springframework/core/util/ArangoErrors.java
- src/main/java/com/arangodb/springframework/core/util/ArangoExceptionTranslator.java
Translate HTTP Status Code `409 - Conflict` to `DataIntegrityViolationException`. Happens e.g. on unique constraint violations.
> Add DataIntegrityViolationException to ExceptionTranslator

- src/main/java/com/arangodb/springframework/core/ArangoOperations.java
- src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
- src/test/java/com/arangodb/springframework/core/template/ArangoTemplateTest.java
I added 2 insert methods to ArangoTemplate where the collection name can be explicitly specified. This can be useful when there is no entity class defined for the object (eg. specified as map). Selecting the target collection this way is already supported by the update methods via the id, so I thought, the same  should work for insert as well.
I also changed the query method in ArangoTemplate to not throw NPE when bindVars parameter is null. The ArangoDatabase Java class allows this method to be called with bindVars == null. When someone changes from the direct Java driver usage to spring-data then these NPEs can be annoying. Also added a new method without bindVars for convenience.
> minor changes to insert and query template methods

- src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
As Spring Beans are singletons by default and we have a multi-threaded environment, we must be careful with operations that change the state of the class.
> Fix race conditions in ArangoTemplate when creating database and collections

- src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactory.java
- src/main/java/com/arangodb/springframework/repository/query/AbstractArangoQuery.java
- src/test/java/com/arangodb/springframework/repository/CustomerRepository.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
- src/test/java/com/arangodb/springframework/testdata/CustomerNameProjection.java
**Changelog:**
- continue supporting `ArangoCursor` in repositories through custom `RepositoryMetadata` (necessary for Spring Data Commons 2.0.7)
- projection support through `ResultProcessor`
> ArangoCursor support in repos (for Spring Data Commons 2.0.7) & projection support

- docs/Drivers/SpringData/Reference/README.md
- src/main/java/com/arangodb/springframework/core/util/AqlUtils.java
- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/main/java/com/arangodb/springframework/repository/query/StringBasedArangoQuery.java
- src/main/java/com/arangodb/springframework/repository/query/derived/DerivedQueryCreator.java
- src/test/java/com/arangodb/springframework/core/util/AqlUtilsTest.java
- src/test/java/com/arangodb/springframework/repository/CustomerRepository.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
I'm opening this PR although it's not finished yet. I want to discuss something:
When building the sort string (`DerivedQueryCreator.buildSortString(sort)`) the property argument is directly embedded into the query. If the sorting properties are user supplied values, this could provide the possibility to perform an AQL injection.
Example:
```java
public interface CustomerRepository extends ArangoRepository<Customer> {
Customer[] findByName(Sort sort, String name);
}
String sort = "age REMOVE e IN customer SORT e.age";  // user provided value
// executes query: 
// FOR e IN customer FILTER e.name == @0 
// SORT e.age REMOVE e IN customer SORT e.age ASC
// RETURN e
final Customer[] retrieved = repository.findByName(Sort.by(sort), "Name");
```
Shouldn't there be some mechanism that this is …
> Support for Pageable and Sort in native queries

- src/main/java/com/arangodb/springframework/annotation/Query.java
- src/test/java/com/arangodb/springframework/repository/OverriddenCrudMethodsRepository.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
With this change, users can override the CRUD methods defined in `ArangoRepository` by using the `@Query` annotation:
```java
public interface SomeRepo extends ArangoRepository<Customer> {
@Override
@Query("RETURN NULL")
Iterable<Customer> findAll();
}
```
> Allow override of CRUD methods of ArangoRepository with @Query

- src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
- src/main/java/com/arangodb/springframework/core/convert/resolver/AbstractResolver.java
- src/main/java/com/arangodb/springframework/core/convert/resolver/LazyLoadingProxy.java
- Support serialization of proxy classes that were created while deserializing lazy references
- Add `ensureResolved()` method to `AbstractResolver.ProxyInterceptor` so that `synchronized resolve()` method is only accessed when the value is not already resolved
> Proxy class support for converter

- ChangeLog.md
- src/main/java/com/arangodb/springframework/core/mapping/DefaultArangoPersistentEntity.java
- src/test/java/com/arangodb/springframework/ArangoTestConfiguration.java
- src/test/java/com/arangodb/springframework/component/TenantProvider.java
- src/test/java/com/arangodb/springframework/core/mapping/MultiTenancyMappingTest.java
This change allows support of multi-tenancy on collection level
> Change SpEL expression parsing for collection names

- src/main/java/com/arangodb/springframework/repository/ArangoExampleConverter.java
- src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java
The query by example feature is broken in the current arangodb-spring-data implementation. The plus sign (+) is not escaped, so string values containing this sign cannot be found by such a query. See my plusSignExampleTest JUnit test.
In this fix I'm using LIKE instead of REGEX_TEST, which I think is much faster and there are much fewer characters to escape.
> fix for query by example: REGEX_TEST changed to LIKE

- src/main/java/com/arangodb/springframework/core/convert/resolver/RelationsResolver.java
- src/test/java/com/arangodb/springframework/core/mapping/RelationsMappingTest.java
The `Relations` annotation accepts multiple edge entities. This resulted in an invalid AQL query being generated.
This fix adds a test for using multiple edge entities with `Relations` and working AQL query generation.
> Fix issue preventing the use of multiple edge entities in @Relations

- src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
- src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java
Handle case when resolved "type to use" is "object" and VelocyPack "source" is "array" in DefaultArangoConverter.
Fixes #147
> DefaultArangoConverter: fix for #147

- src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
- src/main/java/com/arangodb/springframework/core/convert/resolver/RefResolver.java
- src/main/java/com/arangodb/springframework/core/convert/resolver/ReferenceResolver.java
Hello gentlemen.
The project allows you to customize a reference annotation, but only for reading the information. It does not allow customizing the writing of the information.
I am implementing this possibility.
Please accept my pull request.
We are working with a fork separate from yours to be able to use this functionality. But it would be very important to go back to the main project.
> Allow to customize the recording of a reference

- .gitignore
- src/main/java/com/arangodb/springframework/repository/ArangoExampleConverter.java
- src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java
Implementing the regex function in the repository using find by ExampleMatcher.
@giovanniac works with me.
> Regex ExampleMatcher Implementation

- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/ArangoMultiTenancyRepositoryTestConfiguration.java
- src/test/java/com/arangodb/springframework/core/mapping/MultiTenancyDBLevelRepositoryTest.java
Hello, it is the reopening of the task because of the lack of branch
https://github.com/arangodb/spring-data/pull/177
> Create the collection in Multi Tenancy on findOne

- src/test/java/com/arangodb/springframework/repository/CustomerRepository.java
- src/test/java/com/arangodb/springframework/repository/ImportedQueryRepository.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
Hello, this PR is just a unit test to guarantee the functioning of a repository by importing another non-repository interface.
This technique is used to be able to have the same customized query being executed in multiple repositories.
> Imported query repository

- src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java
- src/main/java/com/arangodb/springframework/core/ArangoOperations.java
- src/main/java/com/arangodb/springframework/core/convert/resolver/RefResolver.java
- src/main/java/com/arangodb/springframework/core/convert/resolver/ReferenceResolver.java
- src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
- src/main/java/com/arangodb/springframework/repository/ArangoExampleConverter.java
- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java
Hello gentlemen.
This PR contains an improvement allowing to search for content that is within an array in the document.
Ex: search for the document that has a list of sub documents and in that list has an attribute with a value. 
object `A = {list: [{attribute: value}]}`
I believe that there must be a better way to do the entire ArangoExampleConverter class, but I limited myself to just implementing the missing function. Any day, we can talk about this refactory.
Thanks for listening. Keep up the good work.
> Find By Example With Array

- src/main/java/com/arangodb/springframework/core/ArangoOperations.java
- src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/repository/ShardedCollectionRepositoryTest.java
Workaround to repsert limitations on collections sharded by fields other than `_key` (https://github.com/arangodb/docs/pull/509).
Fixes #185
> repsert based on AQL UPSERT

- src/test/java/com/arangodb/springframework/AbstractArangoTest.java
Hello, how are you?
The PostConstruct annotation is an element of the spring stereotype.
I believe it is not in the right place.
I modified the way it is done, but the end result is the same.
I did this, because I was having trouble running the unit test locally.
Please accept my improvement.
> remove PostConstruct

- ChangeLog.md
- src/main/java/com/arangodb/springframework/annotation/SpelParam.java
- src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactory.java
- src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactoryBean.java
- src/main/java/com/arangodb/springframework/repository/query/ArangoParameterAccessor.java
- src/main/java/com/arangodb/springframework/repository/query/ArangoParameters.java
- src/main/java/com/arangodb/springframework/repository/query/ArangoParametersParameterAccessor.java
- src/main/java/com/arangodb/springframework/repository/query/StringBasedArangoQuery.java
- src/test/java/com/arangodb/springframework/component/FilterGenerator.java
- src/test/java/com/arangodb/springframework/repository/CustomerRepository.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
This allows to use SPEL expressions in user queries provided in `@Query` annotation, enabling to dynamically customize the query depending on the invocation parameters and/or invoking methods on Spring Beans.
Notes:
- SPEL expressions must be wrapped within `#{}`
- SPEL variables can be set annotating method parameters with `@SpelParam("varName")` and referenced with `#varName` in the expression
- the SPEL variable `#collection` is automatically set
- Spring Beans can be referenced with `@myBean` (factory beans with `&myBean`)
Related doc: https://github.com/arangodb/docs/pull/759
Related Slack discussion:
https://arangodb-community.slack.com/archives/C07NV9NAH/p1627588268058100
> implemented SPEL expressions support in StringBasedArangoQuery

- .github/workflows/maven.yml
- pom.xml
- src/main/java/com/arangodb/springframework/core/convert/ArangoCustomConversions.java
- src/main/java/com/arangodb/springframework/core/convert/GeoConverters.java
- src/main/java/com/arangodb/springframework/core/geo/GeoJson.java
- src/main/java/com/arangodb/springframework/core/geo/GeoJsonLineString.java
- src/main/java/com/arangodb/springframework/core/geo/GeoJsonMultiLineString.java
- src/main/java/com/arangodb/springframework/core/geo/GeoJsonMultiPoint.java
- src/main/java/com/arangodb/springframework/core/geo/GeoJsonMultiPolygon.java
- src/main/java/com/arangodb/springframework/core/geo/GeoJsonPoint.java
- src/main/java/com/arangodb/springframework/core/geo/GeoJsonPolygon.java
- src/main/java/com/arangodb/springframework/repository/query/derived/BindParameterBinding.java
- src/main/java/com/arangodb/springframework/repository/query/derived/Criteria.java
- src/main/java/com/arangodb/springframework/repository/query/derived/DerivedQueryCreator.java
- src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java
- src/test/java/com/arangodb/springframework/core/template/ArangoIndexTest.java
- src/test/java/com/arangodb/springframework/repository/CustomerRepository.java
- src/test/java/com/arangodb/springframework/repository/query/derived/DerivedQueryCreatorTest.java
- src/test/java/com/arangodb/springframework/testdata/Customer.java
- src/test/resources/logback-test.xml
This PR adds support to geoJson types (from `com.arangodb.springframework.core.geo`):
- `GeoJsonPoint`
- `GeoJsonMultiPoint`
- `GeoJsonLineString`
- `GeoJsonMultiLineString`
- `GeoJsonPolygon`
- `GeoJsonMultiPolygon`
and to Spring Data geo types (from `org.springframework.data.geo`):
- `Point`
- `Polygon`
All the query derivation capabilities implemented for geospatial points represented as `int[]` have been also implemented for `Point` and `GeoJsonPoint`.
---
fixes https://github.com/arangodb/spring-data-demo/issues/19
> Support of geoJson types and Spring geo types

- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/core/template/ArangoTemplateTest.java
- src/test/java/com/arangodb/springframework/testdata/Customer.java
- src/test/java/com/arangodb/springframework/testdata/Product.java
Refactored query generation by sending DB names always as bindvar instead of concatenating them in the AQL query. 
---
fixes https://github.com/arangodb/spring-data/issues/225
> bugfix dbname string concatenation in query generation

- pom.xml
- src/main/java/com/arangodb/springframework/core/convert/resolver/AbstractResolver.java
- src/test/java/com/arangodb/springframework/repository/AbstractArangoRepositoryTest.java
- src/test/java/com/arangodb/springframework/repository/query/ProductRepository.java
- src/test/java/com/arangodb/springframework/repository/query/derived/DerivedQueryCreatorTest.java
- src/test/java/com/arangodb/springframework/testdata/Product.java
- src/test/java/com/arangodb/springframework/testdata/ShoppingCart.java
Hello gentlemen.
I found a small bug, regarding lombok.
When using some native Java compare function on a list that is using @Ref for a document that is using lombok, Java tries to access the canEqual method.
But lombok puts this method as protected and AbstractResolver cannot call this method.
There is already a form of prevention in AbstractResolver for this scenario, but for other methods. I made the inclusion for this method.
The lombok documentation:
<https://projectlombok.org/features/EqualsAndHashCode>
Thank you for your attention
> [Bug][Lombok] canEqual

- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java
Modify `SimpleArangoRepository#buildPageableClause` for `Pageable.unpaged()` support. In Existing implementation, `Pageable.unpaged()` use case is not handled properly.
> Fix PagingAndSortingRepository fails for Pageable.unpaged()

- src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
- src/main/java/com/arangodb/springframework/core/mapping/ArangoPersistentProperty.java
- src/main/java/com/arangodb/springframework/core/mapping/DefaultArangoPersistentProperty.java
- src/test/java/com/arangodb/springframework/repository/CustomerRepository.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
- src/test/java/com/arangodb/springframework/testdata/Material.java
As described in #269 this is an option to tune performance of fetching referenced entities.
* adjusted the `DefaultArangoConverter` to recognise full entity data in the source which will be read directly instead of using a resolver
* fixed a field naming problem when a document has a property annotated by `@From` or `@To` (including a small refactoring to expose the more specific owner on `ArangoPersistentProperty`)
> Feature: allow embedded entities instead of resolvers

- src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
- src/main/java/com/arangodb/springframework/core/template/DefaultCollectionOperations.java
- src/main/java/com/arangodb/springframework/core/template/DefaultUserOperation.java
- src/main/java/com/arangodb/springframework/core/util/ArangoErrors.java
- src/main/java/com/arangodb/springframework/core/util/ArangoExceptionTranslator.java
- src/test/java/com/arangodb/springframework/core/template/ArangoTemplateTest.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
Fix for #281:
* use recommended `DataAccessUtils.translateIfNecessary()`
* handle some errors in a more specific way:
- errorNumber 1202 as `DataRetrievalFailureException`
- errorNumber 1200 and message with `write-write` conflict as `TransientDataAccessResourceException`
- errorNumber 1200 and message with `_rev` conflict as `OptimisticLockingFailureException`
- errorNumer 1210 and message with `_key` as `DuplicateKeyException`
> [DE-682] #281 better exception translation

- src/main/java/com/arangodb/springframework/core/DocumentNotFoundException.java
- src/main/java/com/arangodb/springframework/core/util/ArangoExceptionTranslator.java
- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
`CrudRepository.deleteById()` has a contract of ignoring unknown ids silently
> [DE-683] ignore unknown id on crud repo deleteById()

- pom.xml
- src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java
- src/main/java/com/arangodb/springframework/core/ArangoOperations.java
- src/main/java/com/arangodb/springframework/core/template/ArangoExtCursor.java
- src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/core/mapping/CustomMappingTest.java
- src/test/java/com/arangodb/springframework/core/mapping/event/AfterLoadEventTest.java
- src/test/java/com/arangodb/springframework/core/mapping/event/DeleteEventTest.java
- src/test/java/com/arangodb/springframework/core/mapping/event/SaveEventTest.java
- src/test/java/com/arangodb/springframework/core/template/ArangoTemplateTest.java
- src/test/java/com/arangodb/springframework/example/polymorphic/template/PolymorphicTemplate.java
- src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
- src/test/java/com/arangodb/springframework/repository/query/graphtraversal/GraphTraversalWithVariousDepthsAndDirectionsTest.java
- `ArangoConverter` is now registered as default user-data serde in the underlying Java driver. This means that it will be automatically used to serialize and deserialize user data, also when using the Java driver directly (obtained via `com.arangodb.springframework.core.ArangoOperations#driver()`). Therefore, in such case, there is no need anymore to invoke entities conversion manually (i.e. manually invoking conversions on `ArangoConverter`).
- renamed `ArangoOperations` methods operating on multiple documents:
- `ArangoOperations#delete(Iterable, ...)`
- `ArangoOperations#update(Iterable, ...)`
- `ArangoOperations#replace(Iterable, ...)`
- `ArangoOperations#insert(Iterable, ...)`
- `ArangoOperations#find(Iterable, ...)`
and related overloaded variants to:
- …
> [DE-38] ArangoTemplate: deserialize return values 

- src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java
- src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
- src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactory.java
- src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactoryBean.java
- src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
- src/test/java/com/arangodb/springframework/AbstractArangoTest.java
- src/test/java/com/arangodb/springframework/ArangoTestConfiguration.java
- src/test/java/com/arangodb/springframework/core/template/ArangoIndexTest.java
- src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java
- src/test/java/com/arangodb/springframework/repository/UserImmutableRepository.java
- src/test/java/com/arangodb/springframework/repository/UserRecordRepository.java
- src/test/java/com/arangodb/springframework/testdata/UserImmutable.java
- src/test/java/com/arangodb/springframework/testdata/UserRecord.java
`SimpleArangoRepository.save()` and `saveAll()` can now be configured to return the entity created from the server result instead of the original (#291). As the may lead to unexpected behaviour, the default is using the old behaviour.
The configuration can be done by a `RepositoryFactoryCustomizer`, which can be prepared in an upcoming `spring-boot-starter` version.
---
fixes #291
> [DE-539] Feature #291 CRUD save returning server result

- src/main/java/com/arangodb/springframework/annotation/ArangoComputedValue.java
- src/main/java/com/arangodb/springframework/annotation/ArangoId.java
- src/main/java/com/arangodb/springframework/annotation/Field.java
- src/main/java/com/arangodb/springframework/annotation/From.java
- src/main/java/com/arangodb/springframework/annotation/FulltextIndexed.java
- src/main/java/com/arangodb/springframework/annotation/GeoIndexed.java
- src/main/java/com/arangodb/springframework/annotation/PersistentIndexed.java
- src/main/java/com/arangodb/springframework/annotation/Ref.java
- src/main/java/com/arangodb/springframework/annotation/Relations.java
- src/main/java/com/arangodb/springframework/annotation/Rev.java
- src/main/java/com/arangodb/springframework/annotation/To.java
- src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java
This PR allows setting properties annotation targets to:
- `ElementType.FIELD`
- `ElementType.METHOD`
- `ElementType.ANNOTATION_TYPE`
> [DE-780] extend properties annotation targets
