src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java

Changes:
- some methods didn't make use of the passed options parameter
- removed unnecessary parameter of `updateDBFields(Iterable, ...)`
- use `getRequiredPersistentEntity()` of Spring instead of custom one

Fix unused options parameters

---

src/main/java/com/arangodb/springframework/core/convert/resolver/RelationsResolver.java

This should fix issue #43.
Although we are setting `lazy = true` on the annotations, it ends up in an infinite recursion. 
The declared type (e.g. `List<...>`) doesn't match with the proxy that is created. That's why the `ConvertingPropertyAccessor.setProperty` converts the proxy, which loads the data and thus making the lazy useless.
Fix: The type in the `RelationsResolver` was hardcoded to `Collection.class` instead of using the type from the property. Not easy to find, especially with this cryptic exceptions.
Plus: The `RelationsResolver.resolve` method should return an entity and not a list. Otherwise we get a list in a list.

Fix for issue #43

---

src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
src/main/java/com/arangodb/springframework/core/util/MetadataUtils.java
src/test/java/com/arangodb/springframework/core/util/MetadataUtilsTest.java

related to obtaining keys from IDs (issue #67).

An optimization for memory and cpu usage, and code reuse 

---

src/test/java/com/arangodb/springframework/repository/HumanBeingRepository.java
src/test/java/com/arangodb/springframework/repository/query/graphtraversal/GraphTraversalWithVariousDepthsAndDirectionsTest.java
src/test/java/com/arangodb/springframework/repository/query/graphtraversal/HumanBeingGraphTraversalTest.java
src/test/java/com/arangodb/springframework/testdata/ChildOf.java
src/test/java/com/arangodb/springframework/testdata/HumanBeing.java

Auto test for graph traversal with various depths & directions

---

src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
src/main/java/com/arangodb/springframework/core/util/MetadataUtils.java
src/test/java/com/arangodb/springframework/core/util/MetadataUtilsTest.java

P.S. Don't forget to reference the PR or the issue when merging this PR (which happened when merging #68 (there should have been a reference to issue #67)).
VCS history should reflect PR and/or issue when they are available.

Fix for issue #85.

---

src/main/java/com/arangodb/springframework/annotation/Key.java
src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
src/main/java/com/arangodb/springframework/core/mapping/ArangoPersistentEntity.java
src/main/java/com/arangodb/springframework/core/mapping/DefaultArangoPersistentEntity.java
src/main/java/com/arangodb/springframework/core/mapping/DefaultArangoPersistentProperty.java
src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
src/test/java/com/arangodb/springframework/core/mapping/FromMappingTest.java
src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java
src/test/java/com/arangodb/springframework/core/mapping/NestedMappingTest.java
src/test/java/com/arangodb/springframework/core/mapping/RefMappingTest.java
src/test/java/com/arangodb/springframework/core/mapping/ToMappingTest.java
src/test/java/com/arangodb/springframework/core/mapping/testdata/BasicTestEntity.java
src/test/java/com/arangodb/springframework/core/template/ArangoTemplateTest.java
src/test/java/com/arangodb/springframework/repository/CustomerRepository.java
src/test/java/com/arangodb/springframework/repository/query/ArangoAqlQueryTest.java
src/test/java/com/arangodb/springframework/repository/query/graphtraversal/GraphTraversalWithVariousDepthsAndDirectionsTest.java
src/test/java/com/arangodb/springframework/testdata/Customer.java
src/test/java/com/arangodb/springframework/testdata/IncompleteCustomer.java
src/test/java/com/arangodb/springframework/testdata/Material.java
src/test/java/com/arangodb/springframework/testdata/Product.java
src/test/resources/arango-named-queries-test.properties

Feature/@id to  key (issue #78)

---

docs/Drivers/SpringData/Reference/README.md

Fix future build error by making headline slugs unique
See https://github.com/arangodb/arangodb/pull/5897/

Docs: Make headlines unique

---

ChangeLog.md
src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
src/main/java/com/arangodb/springframework/core/template/CollectionCacheKey.java
src/main/java/com/arangodb/springframework/core/template/CollectionCacheValue.java
src/main/java/com/arangodb/springframework/core/template/DefaultCollectionOperations.java
src/test/java/com/arangodb/springframework/ArangoMultiTenancyTestConfiguration.java
src/test/java/com/arangodb/springframework/core/mapping/MultiTenancyCollectionLevelMappingTest.java
src/test/java/com/arangodb/springframework/core/mapping/MultiTenancyDBLevelMappingTest.java

This change allows support of multi-tenancy on database level

Add SpEL expression parsing for database names

---

ChangeLog.md
docs/Drivers/SpringData/Reference/Mapping/Events.md
docs/Drivers/SpringData/Reference/Mapping/README.md
src/main/java/com/arangodb/springframework/annotation/EnableArangoAuditing.java
src/main/java/com/arangodb/springframework/config/ArangoAuditingRegistrar.java
src/main/java/com/arangodb/springframework/core/mapping/event/AuditingEventListener.java
src/test/java/com/arangodb/springframework/ArangoTestConfiguration.java
src/test/java/com/arangodb/springframework/AuditorProvider.java
src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java

add support of annotations `@CreatedDate`/`@CreatedBy`/`@LastModifiedDate`/`@LastModifiedBy`

Add auditing support

---

ChangeLog.md
src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
src/test/java/com/arangodb/springframework/core/template/ArangoTemplateTest.java

Fix issue #133 
Fix for ArangoDB < 3.4. (3.4 already works as expected)

Fix ArangoRepository.save() to perform repsert instead of upsert 

---

src/main/java/com/arangodb/springframework/repository/ArangoExampleConverter.java
src/test/java/com/arangodb/springframework/repository/AbstractArangoRepositoryTest.java
src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java
src/test/java/com/arangodb/springframework/repository/query/ShoppingCartRepository.java

Added doWithAssociations implementation for support example query in Reference property of entity.

Fix example query with ref property

---

src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java

#199 DefaultArangoConverter - handle nulls when writing Maps, Arrays and Collections

---

src/main/java/com/arangodb/springframework/repository/ArangoExampleConverter.java
src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java

Hello.
We had created a way to search a list using Spring Example, but we did it by predicting that the list would be "objects / class" only.
Today, we have the problem of doing a search in a list that are of "primitive" types, such as "String" or int.
This is the fix for these cases.
Thanks for listening.

array search

---

src/main/java/com/arangodb/springframework/core/convert/JavaTimeUtil.java
src/main/java/com/arangodb/springframework/core/convert/TimeStringConverters.java
src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java

fixes https://github.com/arangodb/spring-data/issues/226

Mapping support to LocalTime

---

pom.xml
src/main/java/com/arangodb/springframework/annotation/PersistentIndex.java
src/main/java/com/arangodb/springframework/annotation/PersistentIndexed.java
src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java

Hello. 
Please accept or help me improve the pull request. 
I made the inclusion of the deduplicate that did not exist. 
Thanks for listening

[Feature] Add deduplicate in persistent

---

src/main/java/com/arangodb/springframework/repository/query/StringBasedArangoQuery.java

Fixed SPEL evaluation thread safety in string based queries

---

src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
src/test/java/com/arangodb/springframework/core/mapping/GeneralMappingTest.java

fix: TypeInformation equality

---

.github/workflows/maven.yml
integration-tests/pom.xml
pom.xml
src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java
src/test/java/arch/InternalsTest.java
src/test/java/com/arangodb/springframework/ArangoTestConfiguration.java

[DE-707] fix VPACK support

---

.circleci/config.yml
.github/workflows/maven-deploy.yml
.github/workflows/maven-release.yml
integration-tests/pom.xml
pom.xml
src/main/java/com/arangodb/springframework/repository/query/ArangoParameters.java
src/main/java/com/arangodb/springframework/repository/query/ArangoQueryMethod.java

fixing errors in creating parameters caused be changes and removal of deprecations.
Issue #305

fix: Spring-boot 3.3.0

---

src/main/java/com/arangodb/springframework/core/convert/JavaTimeUtil.java
src/test/java/com/arangodb/springframework/core/convert/JavaTimeUtilTest.java

[DE-840] fixed concurrency bug in date conversion

---

pom.xml
src/main/java/com/arangodb/springframework/core/convert/ArangoConverter.java
src/main/java/com/arangodb/springframework/core/convert/DefaultArangoConverter.java
src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java
src/main/java/com/arangodb/springframework/core/template/DefaultCollectionOperations.java
src/main/java/com/arangodb/springframework/core/template/DefaultUserOperation.java
src/main/java/com/arangodb/springframework/core/util/ArangoExceptionTranslator.java
src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactory.java
src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactoryBean.java
src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java
src/test/java/com/arangodb/springframework/core/template/ArangoTemplateTest.java
src/test/java/com/arangodb/springframework/repository/ArangoRepositoryTest.java

Fix delete with revision in ArangoRepository

---

src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java

fix: arangoTemplate bean factory
